using System.Collections.ObjectModel;
using System.IO;
using System.Text.Json;
using SmarterViews.Desktop.Models;

namespace SmarterViews.Desktop.Services;

/// <summary>
/// Service for saving and loading SQL queries generated by AI
/// </summary>
public class SavedSqlQueryService
{
    private readonly string _storageDirectory;
    private const string QueryFileExtension = ".json";

    public SavedSqlQueryService(string? storageDirectory = null)
    {
        _storageDirectory = storageDirectory ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "SmarterViews",
            "SavedQueries");

        if (!Directory.Exists(_storageDirectory))
        {
            Directory.CreateDirectory(_storageDirectory);
        }
    }

    /// <summary>
    /// Saves a SQL query to storage
    /// </summary>
    public async Task SaveQueryAsync(SavedSqlQuery query, CancellationToken cancellationToken = default)
    {
        query.UpdatedAt = DateTime.UtcNow;
        var filePath = GetQueryFilePath(query.Id);
        var json = JsonSerializer.Serialize(query, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(filePath, json, cancellationToken);
    }

    /// <summary>
    /// Loads a SQL query from storage
    /// </summary>
    public async Task<SavedSqlQuery?> LoadQueryAsync(string id, CancellationToken cancellationToken = default)
    {
        var filePath = GetQueryFilePath(id);
        if (!File.Exists(filePath))
        {
            return null;
        }

        var json = await File.ReadAllTextAsync(filePath, cancellationToken);
        return JsonSerializer.Deserialize<SavedSqlQuery>(json);
    }

    /// <summary>
    /// Loads all saved SQL queries
    /// </summary>
    public async Task<ObservableCollection<SavedSqlQuery>> LoadAllQueriesAsync(CancellationToken cancellationToken = default)
    {
        var queries = new ObservableCollection<SavedSqlQuery>();
        var files = Directory.GetFiles(_storageDirectory, $"*{QueryFileExtension}");

        foreach (var file in files)
        {
            try
            {
                var json = await File.ReadAllTextAsync(file, cancellationToken);
                var query = JsonSerializer.Deserialize<SavedSqlQuery>(json);
                if (query != null)
                {
                    queries.Add(query);
                }
            }
            catch (JsonException)
            {
                // Skip invalid files
            }
        }

        // Sort by creation date descending
        return new ObservableCollection<SavedSqlQuery>(queries.OrderByDescending(q => q.CreatedAt));
    }

    /// <summary>
    /// Deletes a SQL query from storage
    /// </summary>
    public Task DeleteQueryAsync(string id)
    {
        var filePath = GetQueryFilePath(id);
        if (File.Exists(filePath))
        {
            File.Delete(filePath);
        }
        return Task.CompletedTask;
    }

    private string GetQueryFilePath(string id)
    {
        return Path.Combine(_storageDirectory, $"{id}{QueryFileExtension}");
    }
}
